import raw from './enrichment.json';
import type { Athlete } from './types';

/**
 * Generated by `scripts/enrich-roster.ts` — do not hand-edit enrichment.json.
 * Stored as `[heightCm | null, birthYear | null]` tuples to keep the shipped
 * payload small; at ~1600 entries an object-per-athlete would roughly triple it.
 */
type Entry = [
  number | null, // heightCm
  number | null, // birthYear
  string | null, // gender
  number | null, // wikipediaLanguages
  number | null, // citizenships
  string | null, // birthCity
  0 | 1, // bornInCapital
  string | null, // positions, slash-separated
];

// TypeScript widens JSON array literals, losing the tuple arity, so the cast
// has to go through `unknown`. The shape is guaranteed by the generator and
// re-checked in tests/enrichment.test.ts.
const ENTRIES = raw.entries as unknown as Record<string, Entry>;

export interface Enrichment {
  heightCm?: number;
  birthYear?: number;
  gender?: 'f' | 'm';
  wikipediaLanguages?: number;
  citizenships?: number;
  birthCity?: string;
  bornInCapital?: boolean;
  positions?: string[];
}

export function enrichmentFor(athleteId: string): Enrichment {
  const entry = ENTRIES[athleteId];
  if (!entry) return {};

  const [heightCm, birthYear, gender, sitelinks, citizenships, birthCity, bornInCapital, positions] =
    entry;
  const out: Enrichment = {};
  if (typeof heightCm === 'number') out.heightCm = heightCm;
  if (typeof birthYear === 'number') out.birthYear = birthYear;
  if (gender === 'f' || gender === 'm') out.gender = gender;
  if (typeof sitelinks === 'number') out.wikipediaLanguages = sitelinks;
  if (typeof citizenships === 'number') out.citizenships = citizenships;
  if (typeof birthCity === 'string') out.birthCity = birthCity;
  if (bornInCapital === 1) out.bornInCapital = true;
  if (typeof positions === 'string' && positions.length > 0) out.positions = positions.split('/');
  return out;
}

export function applyEnrichment(athlete: Athlete): Athlete {
  return { ...athlete, ...enrichmentFor(athlete.id) };
}

export const ENRICHMENT_STATS = {
  athletes: raw.athletes as number,
  withHeight: raw.withHeight as number,
  withBirthYear: raw.withBirthYear as number,
  withGender: (raw as { withGender?: number }).withGender ?? 0,
};
